config/routes.rb
StartupCommunity::Application.routes.draw do
  resources :posts

  resources :business_profiles do
    member do
      get :leave
      get :join
    end
  end

  resources :user_profiles

  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  root 'home#index'
  

  

end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
	has_many :user_business_profiles
	has_many :users, through: :user_business_profiles
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/business_profiles_controller.rb
class BusinessProfilesController < ApplicationController
  before_action :set_business_profile, only: [:show, :edit, :update, :destroy]

  def leave
    @business_profile = BusinessProfile.friendly.find(params[:id])
    current_user.business_profiles.delete(@business_profile)
    redirect_to @business_profile
  end

  def join
    @business_profile = BusinessProfile.friendly.find(params[:id])
    current_user.business_profiles << @business_profile
    redirect_to @business_profile
  end

  # GET /business_profiles
  # GET /business_profiles.json
  def index
    @business_profiles = BusinessProfile.all
  end

  # GET /business_profiles/1
  # GET /business_profiles/1.json
  def show
    @owner = User.find(@business_profile.owner)
  end

  # GET /business_profiles/new
  def new
    @business_profile = BusinessProfile.new
  end

  # GET /business_profiles/1/edit
  def edit
  end

  # POST /business_profiles
  # POST /business_profiles.json
  def create
    @business_profile = BusinessProfile.new(business_profile_params)
    @business_profile.owner = current_user.id
    @business_profile.users << current_user

    respond_to do |format|
      if @business_profile.save
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @business_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_profiles/1
  # PATCH/PUT /business_profiles/1.json
  def update
    respond_to do |format|
      if @business_profile.update(business_profile_params)
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_profiles/1
  # DELETE /business_profiles/1.json
  def destroy
    @business_profile.destroy
    respond_to do |format|
      format.html { redirect_to business_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_profile
      @business_profile = BusinessProfile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_profile_params
      params.require(:business_profile).permit(:name, :email, :phone, :tagline, :about, :url, :blog, :twitter, :facebook, :linkedin, :google, :github, :image, :slug, :employees, :hiring, :latitude, :longitude, :owner)
    end
end

app/helpers/business_profiles_helper.rb
module BusinessProfilesHelper
end

app/views/business_profiles/_form.html.erb
<%= simple_form_for(@business_profile) do |f| %>
  <%= f.error_notification %>
  	<div class="form-group">
    	<%= f.input :name, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :email, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :phone, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :tagline, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :about, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :url, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :blog, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :twitter, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :facebook, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :linkedin, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :google, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :github, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :image, input_html: { class: "form-control"} %>
    </div>

  	<div class="form-group">
    	<%= f.input :employees, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :hiring, input_html: { class: "form-control"} %>
    </div>

    <%= f.button :submit %>
<% end %>

app/views/business_profiles/edit.html.erb
<h1>Editing business_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_profile %> |
<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/index.html.erb
<h1>Listing business_profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Tagline</th>
      <th>About</th>
      <th>Url</th>
      <th>Blog</th>
      <th>Twitter</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Google</th>
      <th>Github</th>
      <th>Image</th>
      <th>Slug</th>
      <th>Employees</th>
      <th>Hiring</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @business_profiles.each do |business_profile| %>
      <tr>
        <td><%= business_profile.name %></td>
        <td><%= business_profile.email %></td>
        <td><%= business_profile.phone %></td>
        <td><%= business_profile.tagline %></td>
        <td><%= business_profile.about %></td>
        <td><%= business_profile.url %></td>
        <td><%= business_profile.blog %></td>
        <td><%= business_profile.twitter %></td>
        <td><%= business_profile.facebook %></td>
        <td><%= business_profile.linkedin %></td>
        <td><%= business_profile.google %></td>
        <td><%= business_profile.github %></td>
        <td><%= business_profile.image %></td>
        <td><%= business_profile.slug %></td>
        <td><%= business_profile.employees %></td>
        <td><%= business_profile.hiring %></td>
        <td><%= business_profile.latitude %></td>
        <td><%= business_profile.longitude %></td>
        <td><%= business_profile.owner %></td>
        <td><%= link_to 'Show', business_profile %></td>
        <td><%= link_to 'Edit', edit_business_profile_path(business_profile) %></td>
        <td><%= link_to 'Destroy', business_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business profile', new_business_profile_path %>

app/views/business_profiles/new.html.erb
<h1>New business_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">

<p>
  <strong>Name:</strong>
  <%= @business_profile.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business_profile.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @business_profile.phone %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @business_profile.tagline %>
</p>

<p>
  <strong>About:</strong>
  <%= @business_profile.about %>
</p>

<p>
  <strong>Url:</strong>
  <%= @business_profile.url %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @business_profile.blog %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @business_profile.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @business_profile.facebook %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @business_profile.linkedin %>
</p>

<p>
  <strong>Google:</strong>
  <%= @business_profile.google %>
</p>

<p>
  <strong>Github:</strong>
  <%= @business_profile.github %>
</p>

<p>
  <strong>Image:</strong>
  <%= @business_profile.image %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @business_profile.slug %>
</p>

<p>
  <strong>Employees:</strong>
  <%= @business_profile.employees %>
</p>

<p>
  <strong>Hiring:</strong>
  <%= @business_profile.hiring %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @business_profile.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @business_profile.longitude %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @owner.user_profile.name %>
</p>
</div>
<div class="col-md-6">
<h3>Associated users:</h3>
<% if @business_profile.users %>
  <ul>
    <% @business_profile.users.each do |user| %>
      <li><%= link_to user.user_profile.name, user_profile_path(user.user_profile) %></li>
    <% end %>
  </ul>
<% end %>

<% if user_signed_in? %>
  <% if current_user.business_profiles.include?(@business_profile) %>
    <%= link_to "Leave this business", leave_business_profile_path, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to "Join this business", join_business_profile_path, class: 'btn btn-success' %>
  <% end %>
<% end %>

</div>
</div>

<%= link_to 'Edit', edit_business_profile_path(@business_profile) %> |
<%= link_to 'Back', business_profiles_path %>