config/routes.rb
StartupCommunity::Application.routes.draw do
  resources :posts

  resources :business_profiles do
    member do
      get :leave
      get :join
    end
  end

  resources :user_profiles

  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  root 'home#index'
  

  

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @post = Post.new
    @posts = @user_profile.user.posts
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user_id = current_user.id

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :name, :email, :phone, :tagline, :about, :url, :blog, :twitter, :facebook, :linkedin, :google, :github, :image, :slug)
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
	
end

app/views/user_profiles/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user_profile.user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/user_profiles/_form.html.erb
<%= simple_form_for(@user_profile) do |f| %>
  <%= f.error_notification %>

  	<div class="form-group">
    	<%= f.input :name, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :email, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :phone, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :tagline, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :about, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :url, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :blog, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :twitter, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :facebook, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :linkedin, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :google, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :github, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :image, input_html: { class: "form-control"} %>
    </div>
  	<div class="form-group">
    	<%= f.input :slug, input_html: { class: "form-control"} %>
    </div>
  

  
    <%= f.button :submit %>
  
<% end %>

app/views/user_profiles/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user_profile.user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Tagline</th>
      <th>About</th>
      <th>Url</th>
      <th>Blog</th>
      <th>Twitter</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Google</th>
      <th>Github</th>
      <th>Image</th>
      <th>Slug</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.user %></td>
        <td><%= user_profile.name %></td>
        <td><%= user_profile.email %></td>
        <td><%= user_profile.phone %></td>
        <td><%= user_profile.tagline %></td>
        <td><%= user_profile.about %></td>
        <td><%= user_profile.url %></td>
        <td><%= user_profile.blog %></td>
        <td><%= user_profile.twitter %></td>
        <td><%= user_profile.facebook %></td>
        <td><%= user_profile.linkedin %></td>
        <td><%= user_profile.google %></td>
        <td><%= user_profile.github %></td>
        <td><%= user_profile.image %></td>
        <td><%= user_profile.slug %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <% if current_page?(user_profile_path(current_user.user_profile)) %>
    <%= link_to "Create your business profile", new_business_profile_path, class: 'btn btn-lg btn-warning' %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-4">
  <h2>My info</h2>

<p>
  <strong>Name:</strong>
  <%= @user_profile.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_profile.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_profile.phone %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @user_profile.tagline %>
</p>

<p>
  <strong>About:</strong>
  <%= @user_profile.about %>
</p>

<p>
  <strong>Url:</strong>
  <%= @user_profile.url %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @user_profile.blog %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @user_profile.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @user_profile.facebook %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @user_profile.linkedin %>
</p>

<p>
  <strong>Google:</strong>
  <%= @user_profile.google %>
</p>

<p>
  <strong>Github:</strong>
  <%= @user_profile.github %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user_profile.image %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user_profile.slug %>
</p>
</div>
<div class="col-md-4">
<h2>My Posts (<span id="posts_count"><%= @user_profile.user.posts.count %></span>)</h2>
<h3>New post:</h3>
<%= simple_form_for @post, remote: true do |f| %>
  <%= f.error_notification %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.input :content, label: 'Post', input_html: { class: "form-control"} %>
    </div>
    <%= f.button :submit %>
<% end %>
<hr>
<h3>Previous posts:</h3>
<% if @posts %>
  <div id="posts">
    <%= render @posts %>
  </div>
<% end %>


</div>
<div class="col-md-4">

  <div class="stats">
    <a href="<%= following_user_path(@user_profile.user) %>" class="btn btn-lg btn-warning">
      <strong id="following" class="stat">
      Following 
        <span class="badge"><%= @user_profile.user.followed_users.count %></span> users
      </strong>
      
    </a>
    </p>
    <a href="<%= followers_user_path(@user_profile.user) %>" class="btn btn-lg btn-warning">
      <strong class="stat">
      Followed by
        <span class="badge" id="followers"><%= @user_profile.user.followers.count %></span> users
      </strong>
      
    </a>
  </div>
<br>
<div class="follow_unfollow">
<% unless current_user == @user_profile.user %>
  <div id="follow_form">
  <% if current_user.following?(@user_profile.user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>
</div>
</div>
</div>
<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>